# Generated by Django 3.0.2 on 2020-02-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='blog.Profil'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
