# Generated by Django 2.2.10 on 2020-02-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200206_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='blog.Profil'),
        ),
    ]
