# Generated by Django 2.2.10 on 2020-02-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200207_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='interet',
        ),
    ]
