# Generated by Django 2.2.10 on 2020-02-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_profil_interet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='interest',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
