# Generated by Django 2.2.10 on 2020-02-07 14:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200207_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
