# Generated by Django 2.2.10 on 2020-02-07 15:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200207_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
